# docker-compose.yml
version: "3"
services:
  app:
    build:
      context: ./backend
    depends_on:
      - postgres
    container_name: pegadas_api
    environment:
      NODE_ENV: test
      PORT: 3000
      WAIT_HOSTS: postgres:5431
    ports:
      - "3000:3000"
    command: "npm run start-builded-app"
  frontend:
    build:
      context: ./frontend
    command: "npm run start-builded-app"
    ports: 
      - "8080:8080"
  postgres:
    image: postgres:10.4
    container_name: postgres
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgroot
      POSTGRES_DB: pegadas
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
      
