# docker-compose.yml
version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
#    links:
#     - postgres
    environment:
      NODE_ENV: test
      PORT: 3000
      WAIT_HOSTS: postgres:5432
    ports:
      - "3000:3000"
    command: "npm run start-builded-app"
    volumes:
      - .:/app/
      - /app/node_modules
  postgres:
    image: postgres:10.4
    ports:
      - "35432:5431"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgroot
      POSTGRES_DB: api_test
      POSTGRES_HOST: 172.17.0.3
